### ISSUE TITLE
模型无法下载

### ISSUE THREAD

**Issue by hongchenxu01** [vearch/vearch#196]
Using TensorFlow backend.
--2020-07-28 11:21:05--  https://storage.googleapis.com/hfl-rc/chinese-bert/chinese_wwm_L-12_H-768_A-12.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 34.64.4.80, 34.64.4.16, 34.64.4.112
Connecting to storage.googleapis.com (storage.googleapis.com)|34.64.4.80|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-28 11:21:09 ERROR 404: Not Found.

Process PackageProcess-1:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "main.py", line 164, in run
    self.build()
  File "main.py", line 77, in build
    self.model = controller.load_model(self.model_name)
  File "/root/go/src/github.com/vearch/vearch/python-algorithm-plugin/src/controller.py", line 91, in load_model
    model = Text()
  File "/root/go/src/github.com/vearch/vearch/python-algorithm-plugin/src/controller.py", line 79, in __init__
    self.model = text.load_model(config.text)
  File "/root/go/src/github.com/vearch/vearch/python-algorithm-plugin/src/text/text.py", line 48, in load_model
    return Text(config)
  File "/root/go/src/github.com/vearch/vearch/python-algorithm-plugin/src/text/text.py", line 38, in __init__
    output_layer_num=1)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/keras_bert/loader.py", line 169, in load_trained_model_from_checkpoint
    **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/keras_bert/loader.py", line 40, in build_model_from_config
    with open(config_file, 'r') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/root/go/src/github.com/vearch/vearch/python-algorithm-plugin/model/chinese_L-12_H-768_A-12/bert_config.json'

**Comment by gDreamcatcher** [comment]
This url is invalid，[chinese_L-12_H-768_A-12.zip](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip) instead. you can download this model and unzip it in model folder, then restart you application.
