### ISSUE TITLE
使用中ps服务进程异常退出

### ISSUE THREAD

**Issue by njlkj** [vearch/vearch#242]
版本: v3.1.0
压测: ab -n 200000 -c 1000 -p ./postdata.txt -T 'content-type: application/json' 'http://10.85.65.114:9001/sift/sift/_search?size=1&client_type=random' 
现象: 容器线程数被耗尽,导致ps进程panic
日志:
```
libgomp: 
libgomp: Thread creation failed: Resource temporarily unavailable
Thread creation failed: Resource temporarily unavailable
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution

libgomp: 
libgomp: Thread creation failed: Resource temporarily unavailable
Thread creation failed: Resource temporarily unavailable
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
goroutine 397222 [syscall]:
github.com/vearch/vearch/ps/engine/gammacb._Cfunc_SearchV2(0x7fd3580015b0, 0x7fca5c00a4c0, 0x0)
        _cgo_gotypes.go:727 +0x4e
github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search.func3(0xc000010550, 0x7fca5c00a4c0, 0x25e23e0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:586 +0x9b
github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search(0xc000010550, 0x180a340, 0xc00213f320, 0xc00364a180, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:586 +0x2ac
github.com/vearch/vearch/ps/storage/raftstore.(*Store).Search(0xc0009ad860, 0x180a340, 0xc00213f320, 0x1833400, 0xc00364a180, 0xc00227b880, 0xc00497b770, 0xc00364a180)
        /env/app/go/src/github.com/vearch/vearch/ps/storage/raftstore/store_read.go:53 +0xb2
github.com/vearch/vearch/ps.(*SearchHandler).Execute(0xc000b4caa8, 0xc000fd1000, 0xc000fd1040, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/handler_document.go:399 +0xb8
github.com/vearch/vearch/util/server/rpc/handler.(*Chain).Execute(0xc000b5ed80, 0x180a340, 0xc00213f320, 0xc000fd1000, 0xc000fd1040, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/util/server/rpc/handler/chain.go:47 +0xe8
reflect.Value.call(0xc000b84400, 0xc00098a830, 0x13, 0x1578913, 0x4, 0xc00497bae8, 0x4, 0x4, 0xc00497baa0, 0x28, ...)
        /env/app/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc000b84400, 0xc00098a830, 0x13, 0xc00497bae8, 0x4, 0x4, 0xc00497bba8, 0x10fce24, 0x12c6900)
        /env/app/go/src/reflect/value.go:308 +0xa4
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*service).call(0xc000b725f0, 0x180a340, 0xc00213f320, 0xc000b84480, 0x13ed1a0, 0xc000fd1000, 0x16, 0x12c6900, 0xc000fd1040, 0x16, ...)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/service.go:361 +0x215
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc000b8a000, 0x180a340, 0xc00213f320, 0xc003793560, 0x0, 0x0, 0xc001613c80)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:529 +0x98c
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc000b8a000, 0xc003793560, 0x1821fa0, 0xc000028460, 0xc00213f320)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:414 +0x1e8
created by github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:396 +0x713

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x1e
rsi    0x3aac
rbp    0x7fad66fb98b0
rsp    0x7fad66fb8e78
r8     0x0
r9     0x16
r10    0x8
r11    0x206
r12    0x3
r13    0x7fad66fb93d0
r14    0x5d
r15    0x2
rip    0x7fd37304b387
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by wxingda** [comment]
并发量太大，服务处理不过来，导致线程积压

**Comment by wxingda** [comment]
发下当时的cpu占用情况

**Comment by njlkj** [comment]
> 并发量太大，服务处理不过来，导致线程积压

通过cgroup限制容器的pids.max=15000,避免影响整个宿主机,从监控能看出来瞬间线程数就飙到了15000,cpu使用率很低
![image](https://user-images.githubusercontent.com/24542486/93613313-494f4880-fa03-11ea-8517-1fa5bdd7056c.png)
![image](https://user-images.githubusercontent.com/24542486/93613399-684dda80-fa03-11ea-9587-938646d17338.png)

这种情况下,怎么避免服务挂掉呢?是否存在线程泄露问题?从监控发现线程一旦涨上来,一直就降不下来了,迟早还是会达到上限

**Comment by wxingda** [comment]
启动的线程数取决于并发量N * CPU核数，可以把并发量先设置成100测测呢

**Comment by njlkj** [comment]
> 启动的线程数取决于并发量N * CPU核数，可以把并发量先设置成100测测呢

N具体是多少,代码中控制的吗?麻烦贴下源码在哪

**Comment by wxingda** [comment]
N就是你的并发量

**Comment by njlkj** [comment]
线程一直没有回收?是不是存在bug
![image](https://user-images.githubusercontent.com/24542486/93736638-8be76f80-fc13-11ea-80f9-a69f374b8694.png)

**Comment by wxingda** [comment]
停止请求后，线程数也下不来吗？

**Comment by njlkj** [comment]
> 停止请求后，线程数也下不来吗？

是的,
```
#  ps -eLf  | grep /vearch/bin/vearch
root      15138      1  23350  0 8122 02:41 ?        00:00:00 /vearch/bin/vearch -conf /vearch/cfg/config.toml ps
root      15138      1  23351  0 8122 02:41 ?        00:00:00 /vearch/bin/vearch -conf /vearch/cfg/config.toml ps
root      15138      1  23352  0 8122 02:41 ?        00:00:00 /vearch/bin/vearch -conf /vearch/cfg/config.toml ps
root      15138      1  23353  0 8122 02:41 ?        00:00:00 /vearch/bin/vearch -conf /vearch/cfg/config.toml ps
.....(省略)
# ps -eLf  | grep /vearch/bin/vearch |wc -l
8123
```

**Comment by wxingda** [comment]
发下建表语句和数据量

**Comment by njlkj** [comment]
**建表和插入数据的脚本**
```
import logging
import pytest
import requests
import json

logging.basicConfig()
logger = logging.getLogger(__name__)

__date__ = '2020-09-17 09:25:00'
__description__ = """ """

ip_db = "10.84.87.49:8817"
ip_data = "10.85.65.114:9001"
db_name = "sift"
space_name = "sift"
fileData = "./sift_learn.json"

def test_createDB():
    logger.info("------------")
    url = "http://" + ip_db + "/db/_create"
    headers = {"content-type": "application/json"}
    data = {
        'name': db_name
    }
    response = requests.put(url, headers=headers, data=json.dumps(data))
    print("db_create---\n" + response.text)
    assert response.status_code == 200

def test_createspace():
    url = "http://" + ip_db + "/space/" + db_name + "/_create"
    headers = {"content-type": "application/json"}
    data = {
        "name": space_name,
        "dynamic_schema": "strict",
        "partition_num": 3,
        "replica_num": 3,
        "engine": {"name": "gamma",
                   "index_size": 9999,
                   "max_size": 100000,
                   "retrieval_type": "IVFPQ",
                   "retrieval_param": {
                        "metric_type": "InnerProduct",
                        "ncentroids": 256,
                        "nsubvector": 32
                   }
                  },
        "properties": {
            "field1": {
                "type": "string",
                "index": True
            },
            "field2": {
                "type": "integer"
            },
            "field3": {
                "type": "float"
            },
            "field4": {
                "type": "vector",
                "dimension": 128
            }
        }
    }
    print(url + "---" + json.dumps(data))
    response = requests.put(url, headers=headers, data=json.dumps(data))
    print("space_create---\n" + response.text)
    assert response.status_code == 200

def test_insterNoId():
    logger.info("insertDataNoId")
    headers = {"content-type": "application/json"}
    with open(fileData, "r") as dataLine1:
        for dataLine in dataLine1:
            data = eval(dataLine)
            id = data["_id"]
            del data["_id"]
            url = "http://" + ip_data + "/" + db_name + "/" + space_name
            response = requests.post(url, headers=headers, data=json.dumps(data))
            print("insertNoID:" + response.text)
            assert response.status_code == 200
```
**插入的数据**
[sift_learn.zip](https://github.com/vearch/vearch/files/5253775/sift_learn.zip)

**查询命令**
```
# echo '{"query":{"sum":[{"field":"field4","feature":[1.0,3.0,11.0,110.0,62.0,22.0,4.0,0.0,43.0,21.0,22.0,18.0,6.0,28.0,64.0,9.0,11.0,1.0,0.0,0.0,1.0,40.0,101.0,21.0,20.0,2.0,4.0,2.0,2.0,9.0,18.0,35.0,1.0,1.0,7.0,25.0,108.0,116.0,63.0,2.0,0.0,0.0,11.0,74.0,40.0,101.0,116.0,3.0,33.0,1.0,1.0,11.0,14.0,18.0,116.0,116.0,68.0,12.0,5.0,4.0,2.0,2.0,9.0,102.0,17.0,3.0,10.0,18.0,8.0,15.0,67.0,63.0,15.0,0.0,14.0,116.0,80.0,0.0,2.0,22.0,96.0,37.0,28.0,88.0,43.0,1.0,4.0,18.0,116.0,51.0,5.0,11.0,32.0,14.0,8.0,23.0,44.0,17.0,12.0,9.0,0.0,0.0,19.0,37.0,85.0,18.0,16.0,104.0,22.0,6.0,2.0,26.0,12.0,58.0,67.0,82.0,25.0,12.0,2.0,2.0,25.0,18.0,8.0,2.0,19.0,42.0,48.0,11.0],"format":"normalization"}],"vector_value": true}}' > postdata.txt

# ab -n 100000 -c 10 -p ./postdata.txt  -T 'content-type: application/json' 'http://10.85.65.114:9001/sift/sift/_search?size=50&client_type=random'
```

**Comment by wxingda** [comment]
`"partition_num": 3,
        "replica_num": 3,`
这样建表，代表启动3个ps，每个ps有3个副本，相当于启动了9个实例，每次搜索，9个实例都会启动`CPU核数`个线程，试下把partition_num和replica_num都设置成1

**Comment by njlkj** [comment]
> `"partition_num": 3, "replica_num": 3,`
> 这样建表，代表启动3个ps，每个ps有3个副本，相当于启动了9个实例，每次搜索，9个实例都会启动`CPU核数`个线程，试下把partition_num和replica_num都设置成1

我试下,但是感觉不能解决线程自动回收问题?

同时再提一个,`vearch/startup.go`一开始就设置了`runtime.GOMAXPROCS(runtime.NumCPU())`,这样在容器环境里运行,获取到的cpu核数是宿主机的核数,而不是容器实际cpu核数,`uber-go/automaxprocs `可以解决这个问题

**Comment by njlkj** [comment]
> `"partition_num": 3, "replica_num": 3,`
> 这样建表，代表启动3个ps，每个ps有3个副本，相当于启动了9个实例，每次搜索，9个实例都会启动`CPU核数`个线程，试下把partition_num和replica_num都设置成1

不应该有12个实例吗? partition_num+replica_num*partition_num=12

**Comment by wxingda** [comment]
> > `"partition_num": 3, "replica_num": 3,`
> > 这样建表，代表启动3个ps，每个ps有3个副本，相当于启动了9个实例，每次搜索，9个实例都会启动`CPU核数`个线程，试下把partition_num和replica_num都设置成1
> 
> 不应该有12个实例吗? partition_num+replica_num*partition_num=12

replica_num里面已经包含了partition，所以是replica_num*partition_num=9

**Comment by itzhusir** [comment]
我这也出现了类似的问题，在docker 容器内运行也会出现线程暴涨但是线程没有回收的情况。在k8s中部署因为k8s对pod启动进程数量的限制，会导致pod频繁重启，并且测试的时候没有什么并发量。版本是最新的，基于ARM平台编译

**Comment by lqhandsome** [comment]
> 

手动在startup.go中设置runtime.GOMAXPROCS(实际分配给容器的核心数)可以解决问题吗
