### ISSUE TITLE
单机模式下./vearch -conf config.toml产生invalid memory error

### ISSUE THREAD

**Issue by rosaline1995** [vearch/vearch#271]
我确认已经改了LD_LIBRARY_PATH（加入了`$vearch/ps/engine/gammacb/lib/lib、$FAISS_HOME、/usr/lib/x86_64-linux-gnu、/usr/local/lib、/usr/local/cuda10.1/lib64/、/opt/OpenBLAS/lib、/usr/local/cuda-10.1/lib64、/opt/OpenBLAS/lib、/lib/x86_64-linux-gnu、/lib64`，感觉应该是所有依赖都考虑到了），
但是按照安装使用文档创建了config.toml文件后（仅把
`data = ["datas/"]`改为
`data = ["/home/rosaline/Desktop/go_project/src/github.com/vearch/vearch/data/"]`，
`log = "logs/`改为
`log = "/home/rosaline/Desktop/go_project/src/github.com/vearch/vearch/logs/"`），
运行`./vearch -conf config.toml`出现以下错误，请问这是为什么呢？

`<pre>2020/11/09 22:59:29 startup.go:65: [ERROR] start server by version:[0.0] commitID:[xxxxx]
2020/11/09 22:59:29 startup.go:74: [ERROR] The Config File Is: config.toml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x125e9fa]

goroutine 1 [running]:
github.com/vearch/vearch/config.(*Config).GetLogFileNum(...)
	/home/rosaline/Desktop/go_project/src/github.com/vearch/vearch/config/config.go:141
main.main()
	/home/rosaline/Desktop/go_project/src/github.com/vearch/vearch/startup.go:95 +0x61a
</pre>`

谢谢！

**Comment by rosaline1995** [comment]
发现了，错误是复制config.toml的时候光标会晃动导致总是选不中第一行的`[global]`于是配置文件漏了一行，对不起打扰了= =
