### ISSUE TITLE
线程无法回收导致服务崩溃

### ISSUE THREAD

**Issue by itzhusir** [vearch/vearch#478]
- 版本：3.2.7
- 平台：ARM64 
- 运行环境：单机docker 容器 和 k8s，单节点
- 现象：持续调用查询接口（约一秒一次，无并发），发现容器内vearch进程启动的线程暴涨，并且在请求结束之后线程没有被回收。k8s中因为有--max-pids限制，会在请求一段时间后线程数达到阈值导致pod被重启。与此issue现象类似：https://github.com/vearch/vearch/issues/242 。并且ARM和x86平台的docker容器中均发现此现象。 
- ARM版编译时参考: https://blog.csdn.net/qq_31955775/article/details/105152190
- 建库语句：
``` 
curl --location --request PUT 'http://host:port/db/_create' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "face_142414249695117707"
}'
```

- 建表语句：
```
curl --location --request PUT 'http://host:port/space/face_142414249695117707/_create' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "test_0001",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 32
        }
    },
    "properties": {
        "vector": {
            "type": "vector",
            "dimension": 2
        }
    }
}'
```

- 查询请求：
``` 
curl --location --request POST 'http://host:port/face_142414249695117707/test_0001/_search' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": {
        "sum": [
            {
                "field": "vector",
                "feature": [
                    0.1111,
                    0.2222
                ]
            }
        ]
    },
    "is_brute_search":1,
    "size": 1
}'
```

**Comment by itzhusir** [comment]
请问有群吗，拉我一下

**Comment by itzhusir** [comment]
- 通过查看进程的堆栈，看到很多线程都hang住了
```
pstack 255
.....
Thread 15 (Thread 0xffff8080bdd0 (LWP 269)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 14 (Thread 0xffff8101bdd0 (LWP 268)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 13 (Thread 0xffff8982bdd0 (LWP 267)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 12 (Thread 0xffff8a03bdd0 (LWP 266)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 11 (Thread 0xffff9284bdd0 (LWP 265)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 10 (Thread 0xffff9705bdd0 (LWP 264)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 9 (Thread 0xffff9b86bdd0 (LWP 263)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 8 (Thread 0xffffa007bdd0 (LWP 262)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 7 (Thread 0xffffa488bdd0 (LWP 261)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 6 (Thread 0xffffa909bdd0 (LWP 260)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 5 (Thread 0xffffa98abdd0 (LWP 259)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 4 (Thread 0xffffb20bbdd0 (LWP 258)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 3 (Thread 0xffffb68cbdd0 (LWP 257)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 2 (Thread 0xffffb70dbdd0 (LWP 256)):
#0  0x0000ffffbb8cda8c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#1  0x0000ffffbb73af54 in blas_thread_server () from /home/vearch/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
#2  0x0000ffffbb8c7800 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbb2917dc in thread_start () from /lib64/libc.so.6
Thread 1 (Thread 0xffffbb979480 (LWP 255)):
#0  runtime.futex () at /usr/local/go/src/runtime/sys_linux_arm64.s:565
#1  0x0000000000431ea8 in runtime.futexsleep (addr=0x1ebd888 <runtime.m0+328>, val=0, ns=-1) at /usr/local/go/src/runtime/os_linux.go:45
#2  0x000000000040d2b8 in runtime.notesleep (n=0x1ebd888 <runtime.m0+328>) at /usr/local/go/src/runtime/lock_futex.go:159
#3  0x000000000043c2a4 in runtime.stoplockedm () at /usr/local/go/src/runtime/proc.go:2085
#4  0x000000000043e0fc in runtime.schedule () at /usr/local/go/src/runtime/proc.go:2617
#5  0x000000000043e488 in runtime.park_m (gp=0x400038d200) at /usr/local/go/src/runtime/proc.go:2851
#6  0x0000000000467de8 in runtime.mcall () at /usr/local/go/src/runtime/asm_arm64.s:172
#7  0x0000000000000000 in ?? ()
``` 

- 使用strace -p 255 查看到的结果是：
```
futex(0x1ebd888, FUTEX_WAIT_PRIVATE, 0, NULL

**Comment by zcdb** [comment]
pstack里面有一堆blas，我猜测是不是在训练过程中，训练的时候搜索的确压力会比较大，你是在训练还没结束的时候搜索的吗？

**Comment by itzhusir** [comment]
> pstack里面有一堆blas，我猜测是不是在训练过程中，训练的时候搜索的确压力会比较大，你是在训练还没结束的时候搜索的吗？

你说的训练是什么意思呢？我这边是先插入了一条向量数据，成功了之后再重复查询这条数据，发现线程会一直增加。而且在停止请求之后线程数也不会降下来

**Comment by zcdb** [comment]
> > pstack里面有一堆blas，我猜测是不是在训练过程中，训练的时候搜索的确压力会比较大，你是在训练还没结束的时候搜索的吗？
> 
> 你说的训练是什么意思呢？我这边是先插入了一条向量数据，成功了之后再重复查询这条数据，发现线程会一直增加。而且在停止请求之后线程数也不会降下来

训练是指训练索引，不过你只插入了一条数据，那就还没有开始训练。你重复查询的话请求正常返回了吗？
另外看你的建表语句，dimension=2，但是nsubvector=32，这种设置是没啥意义的，最好dimension可以整除nsubvector，不过也不应该出现这种情况，你可以设置nsubvector=2试试吗？
