### ISSUE TITLE
批量导入数据，使用hnsw模型，进程崩溃

### ISSUE THREAD

**Issue by WeiYan-Lynn** [vearch/vearch#490]
调用栈如下
#0  runtime.raise () at /opt/buildtools/go-1.14.12/src/runtime/sys_linux_amd64.s:165
#1  0x000000000044f61c in runtime.raisebadsignal (sig=6, c=0x7f6142be9f48) at /opt/buildtools/go-1.14.12/src/runtime/signal_unix.go:815
#2  0x000000000044f9fa in runtime.badsignal (sig=6, c=0x7f6142be9f48) at /opt/buildtools/go-1.14.12/src/runtime/signal_unix.go:934
#3  0x000000000044e4b6 in runtime.sigtrampgo (sig=6, info=0x7f6142bea0f0, ctx=0x7f6142be9fc0) at /opt/buildtools/go-1.14.12/src/runtime/signal_unix.go:456
#4  0x000000000046d4b3 in runtime.sigtramp () at /opt/buildtools/go-1.14.12/src/runtime/sys_linux_amd64.s:389
#5  <signal handler called>
#6  0x00007f6411e964b7 in raise () from /lib64/libc.so.6
#7  0x00007f6411e97ba8 in abort () from /lib64/libc.so.6
#8  0x00007f6412ecc84a in __gnu_cxx::__verbose_terminate_handler ()
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#9  0x00007f6412ecaf47 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#10 0x00007f6412ecaf7d in std::terminate () at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#11 0x00007f6412ecb15a in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7f6130992f00, tinfo=tinfo@entry=0x7f6412f85ad0 <typeinfo for std::system_error>,
    dest=dest@entry=0x7f6412ee6fd4 <std::system_error::~system_error()>)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#12 0x00007f6412ec82f3 in std::__throw_system_error (__i=22)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/ext/new_allocator.h:89
#13 0x00007f64124487f9 in lock (this=<optimized out>) at /opt/buildtools/gcc-8.2.0/include/c++/8.2.0/bits/std_mutex.h:107
#14 lock (this=0x7f6142beaf10, this=0x7f6142beaf10) at /opt/buildtools/gcc-8.2.0/include/c++/8.2.0/bits/std_mutex.h:267
#15 unique_lock (__m=..., this=0x7f6142beaf10) at /opt/buildtools/gcc-8.2.0/include/c++/8.2.0/bits/std_mutex.h:197
**#16 getConnectionsWithLock (level=0, internalId=<optimized out>, this=0x7ee8bf401968)
    at vearch/engine/index/impl/hnswlib/hnswalg.h:997**
#17 hnswlib::HierarchicalNSW<float>::updatePoint (this=this@entry=0x7ee8bf401968, dataPoint=0x7f629f4f92c0, internalId=<optimized out>, updateNeighborProbability=updateNeighborProbability@entry=1)
    at vearch/engine/index/impl/hnswlib/hnswalg.h:846
#18 0x00007f6412440334 in tig_gamma::GammaIndexHNSWLIB::Update(std::vector<long, std::allocator<long> > const&, std::vector<unsigned char const*, std::allocator<unsigned char const*> > const&) ()
    at vearch/engine/index/impl/hnswlib/gamma_index_hnswlib.cc:365
#19 0x00007f641245b388 in tig_gamma::VectorManager::AddRTVecsToIndex() ()
    at vearch/engine/index/retrieval_model.h:177
#20 0x00007f64123dc363 in tig_gamma::GammaEngine::Indexing(int) ()
    at vearch/engine/search/gamma_engine.cc:954
#21 0x00007f6412ee719d in std::execute_native_thread_routine (__p=0x7ed0b32c0c80)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#22 0x00007f64126cde45 in start_thread () from /lib64/libpthread.so.0
#23 0x00007f6411f5d26d in clone () from /lib64/libc.so.6

**Comment by l1351868270** [comment]
@WeiYan-Lynn 使用http短连接试一下,我这边使用长连接会崩；改成短连接就正常了

**Comment by zcdb** [comment]
可以提供一下建表语句吗？另外版本信息能提供一下吗？
