### ISSUE TITLE
设备整机重启后，再次启动ps报错

### ISSUE THREAD

**Issue by WeiYan-Lynn** [vearch/vearch#534]
版本--v3.2.7自己编译
linux机器打系统补丁后重启
启动后两个ps，一个启动成功，一个启动失败
失败信息
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fbc1315cd04 pc=0x7fbb63ff9c99]

runtime stack:
runtime.throw(0x15e3e16, 0x2a)
        /opt/buildtools/go-1.14.12/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /opt/buildtools/go-1.14.12/src/runtime/signal_unix.go:701 +0x46a

goroutine 250 [syscall]:
runtime.cgocall(0x1271df0, 0xc000d236c0, 0x40)
        /opt/buildtools/go-1.14.12/src/runtime/cgocall.go:133 +0x5b fp=0xc000d23690 sp=0xc000d23658 pc=0x4068cb
github.com/vearch/vearch/ps/engine/gamma._Cfunc_DeleteDoc(0x7fbb24000bb0, 0xc0003c2f20, 0x20, 0x0)
        _cgo_gotypes.go:154 +0x4d fp=0xc000d236c0 sp=0xc000d23690 pc=0x109611d
github.com/vearch/vearch/ps/engine/gamma.DeleteDoc.func1(0x7fbb24000bb0, 0xc0003c2f20, 0x20, 0x20, 0xc0003c2f20)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/engine/gamma/gamma.go:61 +0x6a fp=0xc000d236f0 sp=0xc000d236c0 pc=0x1097a0a
github.com/vearch/vearch/ps/engine/gamma.DeleteDoc(0x7fbb24000bb0, 0xc0003c2f20, 0x20, 0x20, 0x203000)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/engine/gamma/gamma.go:61 +0x49 fp=0xc000d23728 sp=0xc000d236f0 pc=0x1096da9
github.com/vearch/vearch/ps/engine/gammacb.(*writerImpl).Write(0xc000ca0230, 0x1844d80, 0xc000d04000, 0xc0006b9f80, 0x0, 0x0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/engine/gammacb/writer.go:77 +0x5e7 fp=0xc000d23880 sp=0xc000d23728 pc=0x1211527
github.com/vearch/vearch/ps/storage/raftstore.(*Store).innerApply(0xc000d08000, 0xc043592e11, 0x26, 0x2a, 0x5e, 0xc000d04040, 0x1396760, 0xc0002f9fa0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/storage/raftstore/raft_state_machine.go:120 +0x32f fp=0xc000d238e8 sp=0xc000d23880 pc=0x120266f
github.com/vearch/vearch/ps/storage/raftstore.(*Store).Apply(0xc000d08000, 0xc043592e11, 0x26, 0x2a, 0x5e, 0x1396760, 0xc0002f9fa0, 0x0, 0x0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/storage/raftstore/raft_state_machine.go:88 +0x12a fp=0xc000d239e8 sp=0xc000d238e8 pc=0x1201eba
github.com/vearch/vearch/vendor/github.com/tiglabs/raft.(*raftFsm).recoverCommit(0xc000f403c0, 0x15f1796, 0x34)
/clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/vendor/github.com/tiglabs/raft/raft_fsm.go:254 +0xc2 fp=0xc000d23a68 sp=0xc000d239e8 pc=0x10133c2
github.com/vearch/vearch/vendor/github.com/tiglabs/raft.newRaftFsm(0xc00033a370, 0xc00141a3c0, 0xc0002a8a80, 0x27, 0x0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/vendor/github.com/tiglabs/raft/raft_fsm.go:121 +0x597 fp=0xc000d23bc8 sp=0xc000d23a68 pc=0x1011417
github.com/vearch/vearch/vendor/github.com/tiglabs/raft.newRaft(0xc00033a370, 0xc00141a3c0, 0x0, 0x0, 0x0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/vendor/github.com/tiglabs/raft/raft.go:136 +0xdf fp=0xc000d23cf0 sp=0xc000d23bc8 pc=0x100aabf
github.com/vearch/vearch/vendor/github.com/tiglabs/raft.(*RaftServer).CreateRaft(0xc0006fc480, 0xc00141a3c0, 0x0, 0x0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/vendor/github.com/tiglabs/raft/server.go:135 +0x89 fp=0xc000d23d78 sp=0xc000d23cf0 pc=0x1023c09
github.com/vearch/vearch/ps/storage/raftstore.(*Store).Start(0xc000d08000, 0xc000fa8000, 0x2)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/storage/raftstore/store.go:178 +0x49f fp=0xc000d23ea8 sp=0xc000d23d78 pc=0x1204d2f
github.com/vearch/vearch/ps.(*Server).LoadPartition(0xc00020fb80, 0x1844dc0, 0xc0000440e0, 0x122, 0x0, 0x0, 0x0, 0x0)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/partition_service.go:124 +0x2f1 fp=0xc000d23f48 sp=0xc000d23ea8 pc=0x121afc1
github.com/vearch/vearch/ps.(*Server).recoverPartitions.func1(0xc00019a680, 0xc00020fb80, 0x1844dc0, 0xc0000440e0, 0x122)
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/partition_service.go:247 +0x118 fp=0xc000d23fb8 sp=0xc000d23f48 pc=0x1220408
runtime.goexit()
        /opt/buildtools/go-1.14.12/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000d23fc0 sp=0xc000d23fb8 pc=0x46b5a1
created by github.com/vearch/vearch/ps.(*Server).recoverPartitions
        /clouddragonData/mesos/slave/slaves/bd186a9b-2d1a-4487-851b-12bb98537df4-S237/frameworks/bd186a9b-2d1a-4487-851b-12bb98537df4-14133/executors/mesos-jenkins-872b165d188d41adb8f7e8e103f34591-ccs_service_eule/runs/1124d164-98e6-4e36-903f-840b76c28dc2/jenkins/workspace/p71f3beb4108b4f2a86fc778c8742a64f/SparkleSearch_SemanticMatch_compile_vearch2/SparkleSearch_SemanticMatch/vectorstorage/thirdparty/src/github.com/vearch/vearch/ps/partition_service.go:243 +0xad
未能生成coredump文件

**Comment by rrjia** [comment]
京东上线用的真的是这个嘛，感觉各种问题挺多的
