### ISSUE TITLE
bazel 3.4.1 + openjdk-11 + gcc 9.4(编译安装) + clang-8 环境编译scann不通过报错:

### ISSUE THREAD

**Issue by frederic89** [vearch/vearch#707]
在进入到Bazel编译时报错如下，已经科学上网
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //:build_pip_pkg (1 packages loaded, 0 targets configured)
Analyzing: target //:build_pip_pkg (6 packages loaded, 5 targets configured)
Analyzing: target //:build_pip_pkg (6 packages loaded, 5 targets configured)
Analyzing: target //:build_pip_pkg (6 packages loaded, 5 targets configured)
INFO: Repository local_config_cc instantiated at:
no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cc_autoconf defined at:
/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/cc_configure.bzl:143:30: in
ERROR: An error occurred during the fetch of repository 'local_config_cc':
Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125
configure_unix_toolchain(<3 more arguments>)
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 352, in configure_unix_toolchain
_find_generic(repository_ctx, <3 more arguments>)
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 322, in _find_generic
auto_configure_fail(msg)
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, in auto_configure_fail
fail(<1 more arguments>)

Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: /root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/src/tools/launcher/BUILD:9:14: @bazel_tools//src/tools/launcher:launcher depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125
configure_unix_toolchain(<3 more arguments>)
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 352, in configure_unix_toolchain
_find_generic(repository_ctx, <3 more arguments>)
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 322, in _find_generic
auto_configure_fail(msg)
File "/root/.cache/bazel/_bazel_root/1fd1b682e65630d5ac25a25ae95f5b5c/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, in auto_configure_fail
fail(<1 more arguments>)

Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: Analysis failed
INFO: Elapsed time: 138.537s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (20 packages loaded, 59 targets configured)
FAILED: Build did NOT complete successfully (20 packages loaded, 59 targets configured)
scann bazel build error
-- SCANN BUILD ERROR, EXEC_RET_VAL=2
CMake Error at CMakeLists.txt:233 (EXIT):
Unknown CMake command "EXIT".

**bazel 3.4.1 + openjdk-11 + gcc 9.4(编译安装) + clang-8**
> bazel 3.4.1 安装自 https://mirrors.huaweicloud.com/bazel/3.4.1/bazel-3.4.1-installer-linux-x86_64.sh
> openjdk 安装自yum install
> (gcc+clang 在env的中配置
> echo "export CC=clang" >> /etc/bashrc
> echo "export CXX=clang++" >> /etc/bashrc
> echo "export PATH=$PATH:/usr/local/clang/bin" >> /etc/bashrc)

**Comment by zcdb** [comment]
CC和CXX配置成gcc和g++的路径
